#!/usr/bin/env bash
#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other /bin/sh around, it should work.
#
#   (2) Runs in "batch" mode, which makes it easier to run this script from an
#       IDE and to still see the output if there are errors.
#
#   (3) This script is generated as part of the normal Gradle build lifecycle.
#       You can use it to wrap Gradle itself, e.g. you could do 'bash gradlew build'.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}	# leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]					# next if $app_path is a symlink
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}						# remove leading '... -> ' text
    case $link in							#(
      /*)	app_path=$link ;; 					# absolute symlink
      *)	app_path=$APP_HOME$link ;; 				# relative symlink
    esac
done

APP_HOME=$( cd "${APP_HOME:-.}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_JAR="gradle-wrapper.jar"

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != unlimited.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* / MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

JAVACMD=$( find "$JAVA_HOME" -type f -name javac ) 2>/dev/null
[ -z "$JAVACMD" ] && JAVACMD=javac

# Iterate over the JVM arguments and collect values.
# With the while read technique we load JVM arguments line-by-line while
# still supporting shell globbing and relative + absolute paths.
# The downside is that if there are spaces in a JVM argument, it needs
# to be quoted.

while IFS= read -r arg; do
  case $arg in                                #(
    -*)  false ;;                            # disable globbing
    *)   : ;;                                # enable globbing
  esac
  cmd="$cmd $(printf '%s\n' "$arg" | sed -e 's/[^-[:alnum:]\/.]/\\&/g')"
done <<< "$DEFAULT_JVM_OPTS"

# Collect all arguments for the java command, and put the console output in a temp file.
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" has processed all potential command line end-of-line indicators.
# See https://unix.stackexchange.com/questions/82191/which-terminal-closed-stdin-on-truncated-line
if ! { echo "$@"; } | grep -qE  '(^-D|-[a-zA-Z]|^[^-]|--$)'; then
    exec >&2
    echo 'Failed to escape some characters, using jshell to escape arguments, falling back to external tool.'
    exec sh "$0" "$@"
fi

trap "rm -f \"$tmp\"" EXIT
tmp=$(mktemp -d) || { (exit 1); return $?; }
sed -n -e "1h;x;\$!H;\$!d;x" > "$tmp/defines.txt" <<-GRADLE_EOF
# This script uses "jshell" for escaping.
set -o nounset
IFS=$'\n'
for arg in $@
do
  arg_escaped=\$(jshell -e "println(java.lang.String.format(\"%s\", java.nio.file.Files.readAllLines(java.nio.file.Paths.get(\\\"/dev/stdin\\\")).get(0)))" <<< "\$arg")
  cmd="\$cmd \"\$arg_escaped\""
done
exec java \$cmd
GRADLE_EOF

exec "$JAVA_HOME/bin/java" \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"
